/*
 * Git History: log, diff, show, reset, revert
 *
 * C++17 industry-style case study:
 * A repository maintenance audit tool.
 *
 * The program creates a temporary Git repository, builds a realistic
 * development history, and uses Git commands to inspect and reason about
 * that history.
 *
 * Demonstrated concepts:
 *   - commit history
 *   - repository state
 *   - git log
 *   - git show
 *   - git diff
 *   - git reset
 *   - git revert
 *   - branches and merges
 *   - revision expressions
 *   - reflog
 *   - file-specific history
 *   - validation
 *   - process execution
 *   - machine-readable output
 *   - complexity and operational trade-offs
 *
 * Requirements:
 *   - C++17 or later
 *   - Git executable available on PATH
 *
 * No external C++ libraries are required.
 */

#include <array>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#ifdef _WIN32
#include <windows.h>
#endif

namespace fs = std::filesystem;

struct CommandResult {
    int exitCode{};
    std::string output;
};

class GitError : public std::runtime_error {
public:
    explicit GitError(const std::string& message)
        : std::runtime_error(message) {}
};

static std::string quoteShellArgument(const std::string& value) {
#ifdef _WIN32
    /*
     * Windows cmd.exe quoting is sufficient for the controlled arguments
     * generated by this demonstration. We avoid accepting arbitrary shell
     * expressions from the user.
     */
    std::string result = "\"";
    for (char character : value) {
        if (character == '"') {
            result += "\\\"";
        } else {
            result += character;
        }
    }
    result += "\"";
    return result;
#else
    /*
     * POSIX single-quote escaping prevents spaces and shell metacharacters
     * from being interpreted as shell syntax.
     */
    std::string result = "'";
    for (char character : value) {
        if (character == '\'') {
            result += "'\\''";
        } else {
            result += character;
        }
    }
    result += "'";
    return result;
#endif
}

static CommandResult runShellCommand(
    const std::string& command,
    const fs::path& workingDirectory
) {
    /*
     * Redirect stderr to stdout so that the complete diagnostic is captured.
     * The command itself is assembled from controlled arguments in this
     * program rather than arbitrary user input.
     */
    std::string fullCommand;

#ifdef _WIN32
    fullCommand =
        "cd /d " + quoteShellArgument(workingDirectory.string()) +
        " && " + command + " 2>&1";
#else
    fullCommand =
        "cd " + quoteShellArgument(workingDirectory.string()) +
        " && " + command + " 2>&1";
#endif

#ifdef _WIN32
    FILE* pipe = _popen(fullCommand.c_str(), "r");
#else
    FILE* pipe = popen(fullCommand.c_str(), "r");
#endif

    if (!pipe) {
        throw GitError("Unable to start command: " + command);
    }

    std::array<char, 4096> buffer{};
    std::string output;

    while (fgets(buffer.data(), static_cast<int>(buffer.size()), pipe)) {
        output += buffer.data();
    }

#ifdef _WIN32
    const int exitCode = _pclose(pipe);
#else
    const int exitCode = pclose(pipe);
#endif

    return {exitCode, output};
}

static std::string buildCommand(
    const std::vector<std::string>& arguments
) {
    std::ostringstream command;

    for (std::size_t index = 0; index < arguments.size(); ++index) {
        if (index != 0) {
            command << ' ';
        }
        command << quoteShellArgument(arguments[index]);
    }

    return command.str();
}

static CommandResult gitCommand(
    const fs::path& repository,
    const std::vector<std::string>& arguments,
    bool check = true
) {
    std::vector<std::string> fullArguments;
    fullArguments.push_back("git");

    for (const auto& argument : arguments) {
        fullArguments.push_back(argument);
    }

    const auto result = runShellCommand(
        buildCommand(fullArguments),
        repository
    );

    if (check && result.exitCode != 0) {
        throw GitError(
            "Git command failed:\n" +
            buildCommand(fullArguments) +
            "\n\n" +
            result.output
        );
    }

    return result;
}

static std::string gitText(
    const fs::path& repository,
    const std::vector<std::string>& arguments,
    bool check = true
) {
    auto result = gitCommand(repository, arguments, check);

    while (!result.output.empty() &&
           (result.output.back() == '\n' ||
            result.output.back() == '\r')) {
        result.output.pop_back();
    }

    return result.output;
}

static void section(const std::string& title) {
    std::cout << "\n" << std::string(78, '=') << "\n";
    std::cout << title << "\n";
    std::cout << std::string(78, '=') << "\n";
}

static void writeFile(
    const fs::path& repository,
    const fs::path& relativePath,
    const std::string& content
) {
    const fs::path target = repository / relativePath;

    fs::create_directories(target.parent_path());

    std::ofstream output(target, std::ios::binary);
    if (!output) {
        throw GitError("Unable to write " + target.string());
    }

    output << content;
}

static std::string readFile(
    const fs::path& repository,
    const fs::path& relativePath
) {
    const fs::path target = repository / relativePath;

    std::ifstream input(target, std::ios::binary);
    if (!input) {
        throw GitError("Unable to read " + target.string());
    }

    std::ostringstream contents;
    contents << input.rdbuf();
    return contents.str();
}

static void showStatus(const fs::path& repository) {
    std::cout
        << gitText(
               repository,
               {"status", "--short", "--branch"}
           )
        << "\n";
}

static std::string createCommit(
    const fs::path& repository,
    const std::string& message
) {
    gitCommand(repository, {"add", "-A"});
    gitCommand(repository, {"commit", "-m", message});

    return gitText(repository, {"rev-parse", "HEAD"});
}

static std::string shortHash(
    const fs::path& repository,
    const std::string& revision = "HEAD"
) {
    return gitText(
        repository,
        {"rev-parse", "--short", revision}
    );
}

static void configureRepository(const fs::path& repository) {
    gitCommand(repository, {"init", "-b", "main"});

    /*
     * Repository-local identity prevents the demonstration from modifying
     * the user's global Git identity.
     */
    gitCommand(
        repository,
        {"config", "user.name", "Git History Demonstration"}
    );

    gitCommand(
        repository,
        {
            "config",
            "user.email",
            "git-history-demo@example.invalid"
        }
    );
}

static fs::path createRepository(const fs::path& root) {
    const fs::path repository = root / "git-history-demo";

    fs::create_directories(repository);
    configureRepository(repository);

    writeFile(
        repository,
        "README.md",
        "# Git History Demonstration\n\nInitial project.\n"
    );

    writeFile(
        repository,
        "app.txt",
        "Application version 1\n"
    );

    createCommit(repository, "Initial project");

    writeFile(
        repository,
        "app.txt",
        "Application version 1\nFeature A enabled\n"
    );

    createCommit(repository, "Add feature A");

    writeFile(
        repository,
        "config.txt",
        "mode=development\nlogging=basic\n"
    );

    createCommit(repository, "Add development configuration");

    return repository;
}

static void explainRepositoryModel() {
    section("1. Repository and history model");

    std::cout << R"(
Git history consists of commits connected through parent relationships.

A linear history:

    A --- B --- C --- D

A commit records a snapshot through a tree plus metadata and parent
relationships.

The three practical states are:

    HEAD
        The currently referenced commit.

    Index
        The staging area used to construct the next commit.

    Working tree
        The files currently present on disk.

The distinction matters because:

    git diff
        compares working tree with index.

    git diff --cached
        compares index with HEAD.

    git diff HEAD
        compares current working/index state with HEAD.

Branches are movable references to commits. A commit ID identifies a
particular Git object and therefore changes when the committed content,
parents, or relevant metadata changes.
)";
}

static void demonstrateLog(const fs::path& repository) {
    section("2. git log");

    std::cout << R"(
git log answers questions about commit history.

Common forms:

    git log
    git log --oneline
    git log --graph --decorate --oneline --all
    git log -n 5
    git log --stat
    git log -p
    git log -- path/to/file
)";

    std::cout << "\nFull log:\n";
    std::cout << gitText(repository, {"log"}) << "\n";

    std::cout << "\nCompact log:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--oneline", "--decorate"}
           )
        << "\n";

    std::cout << "\nGraph:\n";
    std::cout
        << gitText(
               repository,
               {
                   "log",
                   "--graph",
                   "--decorate",
                   "--oneline",
                   "--all"
               }
           )
        << "\n";

    std::cout << "\nHistory affecting app.txt:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--oneline", "--", "app.txt"}
           )
        << "\n";
}

static void demonstrateShow(const fs::path& repository) {
    section("3. git show");

    std::cout << R"(
git show inspects a particular Git object.

For a commit, it commonly displays:

    - object ID
    - author and committer
    - commit message
    - parent information
    - patch introduced by the commit

A path can also be retrieved from a particular commit with:

    git show HEAD:path/to/file
)";

    std::cout << "\nLatest commit summary:\n";
    std::cout
        << gitText(
               repository,
               {"show", "--stat", "HEAD"}
           )
        << "\n";

    std::cout << "\napp.txt stored in HEAD:\n";
    std::cout
        << gitText(
               repository,
               {"show", "HEAD:app.txt"}
           )
        << "\n";
}

static void demonstrateDiff(const fs::path& repository) {
    section("4. git diff");

    std::cout << R"(
Git diff is a comparison operation.

The important everyday comparisons are:

    git diff
        Working tree versus index.

    git diff --cached
        Index versus HEAD.

    git diff HEAD
        Working tree/index versus HEAD.

    git diff A B
        Commit A versus commit B.
)";

    writeFile(
        repository,
        "app.txt",
        "Application version 1\n"
        "Feature A enabled\n"
        "Feature B experimental\n"
    );

    std::cout << "\nUnstaged change:\n";
    showStatus(repository);

    std::cout << "\ngit diff:\n";
    std::cout << gitText(repository, {"diff"}) << "\n";

    gitCommand(repository, {"add", "app.txt"});

    std::cout << "\nAfter staging:\n";
    showStatus(repository);

    std::cout << "\ngit diff:\n";
    const auto unstaged = gitText(repository, {"diff"});
    std::cout << (unstaged.empty() ? "(none)" : unstaged) << "\n";

    std::cout << "\ngit diff --cached:\n";
    std::cout
        << gitText(repository, {"diff", "--cached"})
        << "\n";

    std::cout << "\ngit diff HEAD:\n";
    std::cout
        << gitText(repository, {"diff", "HEAD"})
        << "\n";

    gitCommand(repository, {"restore", "--staged", "app.txt"});
    gitCommand(repository, {"restore", "app.txt"});

    std::cout << "\nRestored state:\n";
    showStatus(repository);

    std::cout << "\nComparison between older and current commits:\n";
    std::cout
        << gitText(
               repository,
               {"diff", "HEAD~2", "HEAD"}
           )
        << "\n";
}

static void demonstrateReset(const fs::path& repository) {
    section("5. git reset");

    std::cout << R"(
reset changes the current branch position and, depending on its mode, the
index and working tree.

    --soft
        Move HEAD/branch only.

    --mixed
        Move HEAD/branch and reset the index.
        Preserve working-tree content.

    --hard
        Move HEAD/branch, reset the index, and reset the working tree.
        Uncommitted content may be lost.

The operation is therefore state-sensitive and potentially destructive.
)";

    writeFile(
        repository,
        "reset-demo.txt",
        "Temporary reset demonstration commit.\n"
    );

    createCommit(
        repository,
        "Temporary reset demonstration commit"
    );

    writeFile(
        repository,
        "reset-demo.txt",
        "Temporary reset demonstration commit.\n"
        "Uncommitted local modification.\n"
    );

    gitCommand(
        repository,
        {"reset", "--mixed", "HEAD~1"}
    );

    std::cout << "\nAfter mixed reset:\n";
    showStatus(repository);

    std::cout
        << readFile(repository, "reset-demo.txt")
        << "\n";

    /*
     * The working tree was intentionally retained by mixed reset.
     * Restore it before continuing.
     */
    gitCommand(repository, {"restore", "reset-demo.txt"});
    gitCommand(repository, {"clean", "-fd"});

    writeFile(
        repository,
        "soft-demo.txt",
        "Temporary soft reset demonstration.\n"
    );

    createCommit(
        repository,
        "Temporary soft reset commit"
    );

    gitCommand(
        repository,
        {"reset", "--soft", "HEAD~1"}
    );

    std::cout << "\nAfter soft reset:\n";
    showStatus(repository);

    /*
     * Return the temporary repository to a clean state.
     */
    gitCommand(repository, {"reset", "--mixed", "HEAD"});
    gitCommand(repository, {"restore", "."});
    gitCommand(repository, {"clean", "-fd"});
}

static void demonstrateRevert(const fs::path& repository) {
    section("6. git revert");

    std::cout << R"(
revert creates a new commit that reverses an existing commit.

Suppose:

    A --- B --- C

If C is reverted:

    A --- B --- C --- D

D is a new commit containing the inverse change.

This preserves C in the history. Revert can therefore be used to undo a
published change without rewriting the existing sequence of commits.
)";

    writeFile(
        repository,
        "revert-demo.txt",
        "Feature added for revert demonstration.\n"
    );

    const std::string target = createCommit(
        repository,
        "Add feature that will be reverted"
    );

    std::cout << "Commit being reverted: " << target << "\n";

    gitCommand(
        repository,
        {"revert", "--no-edit", target}
    );

    std::cout << "\nHistory after revert:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--oneline", "-5"}
           )
        << "\n";

    std::cout << "\nFile after revert:\n";
    std::cout
        << readFile(repository, "revert-demo.txt")
        << "\n";
}

static void demonstrateRevisionExpressions(
    const fs::path& repository
) {
    section("7. Revision expressions");

    std::cout << R"(
Git provides compact revision syntax.

    HEAD
        Current commit.

    HEAD~1
        First-parent ancestor.

    HEAD~2
        Two first-parent steps backward.

    HEAD^
        First parent.

    HEAD^2
        Second parent of a merge commit.

Ranges:

    A..B
        Commits reachable from B but not A.

    A...B
        Symmetric history difference.

For diff, A...B uses the merge base as the comparison starting point.
)";

    std::cout << "\nHEAD:\n";
    std::cout
        << gitText(repository, {"rev-parse", "HEAD"})
        << "\n";

    std::cout << "\nHEAD~1:\n";
    std::cout
        << gitText(repository, {"rev-parse", "HEAD~1"})
        << "\n";

    std::cout << "\nParent relationships:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--oneline", "--parents", "-6"}
           )
        << "\n";
}

static void demonstrateMergeHistory(
    const fs::path& repository
) {
    section("8. Merge-aware history");

    std::cout << R"(
Merge commits have multiple parents.

Example:

              C --- D
             /       \
    A --- B --------- M

M can be inspected with:

    git show M
    git rev-parse M^
    git rev-parse M^2

`git log --first-parent` follows the mainline parent chain.
)";

    const std::string mainBranch =
        gitText(repository, {"branch", "--show-current"});

    gitCommand(
        repository,
        {"switch", "-c", "history-feature"}
    );

    writeFile(
        repository,
        "feature.txt",
        "Feature branch change.\n"
    );

    createCommit(
        repository,
        "Add feature branch change"
    );

    gitCommand(
        repository,
        {"switch", mainBranch}
    );

    writeFile(
        repository,
        "mainline.txt",
        "Main branch change.\n"
    );

    createCommit(
        repository,
        "Add mainline change"
    );

    gitCommand(
        repository,
        {
            "merge",
            "--no-ff",
            "history-feature",
            "-m",
            "Merge history feature"
        }
    );

    std::cout << "\nMerged graph:\n";
    std::cout
        << gitText(
               repository,
               {
                   "log",
                   "--graph",
                   "--decorate",
                   "--oneline",
                   "--all"
               }
           )
        << "\n";

    std::cout << "\nFirst-parent history:\n";
    std::cout
        << gitText(
               repository,
               {
                   "log",
                   "--first-parent",
                   "--oneline",
                   "-8"
               }
           )
        << "\n";

    gitCommand(
        repository,
        {"branch", "-D", "history-feature"}
    );
}

static void demonstrateFileHistory(
    const fs::path& repository
) {
    section("9. File-specific history");

    std::cout << R"(
History can be restricted to a file.

Examples:

    git log -- path
    git log -p -- path
    git log --follow -- path

`git blame` answers a different question: which commit is associated with
each line in the current version of a file.
)";

    std::cout << "\napp.txt history:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--oneline", "--", "app.txt"}
           )
        << "\n";

    std::cout << "\napp.txt patches:\n";
    std::cout
        << gitText(
               repository,
               {"log", "-p", "--", "app.txt"}
           )
        << "\n";

    std::cout << "\nLine attribution:\n";
    std::cout
        << gitText(
               repository,
               {"blame", "app.txt"}
           )
        << "\n";
}

static void demonstratePrettyFormats(
    const fs::path& repository
) {
    section("10. Structured history output");

    std::cout << R"(
For scripts, explicitly selecting fields is more stable than depending on
human-oriented formatting.

Useful placeholders include:

    %H  full hash
    %h  abbreviated hash
    %an author name
    %ae author email
    %ad author date
    %s  subject
    %p  parent hashes
)";

    std::cout
        << gitText(
               repository,
               {
                   "log",
                   "--pretty=format:%h | %ad | %an | %s",
                   "--date=short",
                   "-10"
               }
           )
        << "\n";
}

static void demonstrateReflog(
    const fs::path& repository
) {
    section("11. Reflog");

    std::cout << R"(
The reflog records local movements of references.

A typical recovery investigation is:

    git reflog
    git show <candidate>
    git branch recovery <candidate>

Reflog is local. It is not a guaranteed long-term backup, and entries may
eventually expire.
)";

    std::cout
        << gitText(
               repository,
               {"reflog", "-10"}
           )
        << "\n";
}

static void runValidation(
    const fs::path& repository
) {
    section("12. Validation and operational checks");

    const auto headResult = gitCommand(
        repository,
        {"rev-parse", "HEAD"},
        false
    );

    const bool headExists =
        headResult.exitCode == 0 &&
        !headResult.output.empty();

    const int commitCount = std::stoi(
        gitText(
            repository,
            {"rev-list", "--count", "HEAD"}
        )
    );

    const auto parentResult = gitCommand(
        repository,
        {"rev-parse", "HEAD~1"},
        false
    );

    const auto showResult = gitCommand(
        repository,
        {"show", "--quiet", "HEAD"},
        false
    );

    const std::string status =
        gitText(repository, {"status", "--porcelain"});

    const bool clean = status.empty();

    const std::vector<std::pair<std::string, bool>> checks{
        {"HEAD resolves", headExists},
        {"At least three commits exist", commitCount >= 3},
        {"HEAD~1 resolves", parentResult.exitCode == 0},
        {"git show can inspect HEAD", showResult.exitCode == 0},
        {"Working tree is clean", clean}
    };

    bool allPassed = true;

    for (const auto& [description, passed] : checks) {
        std::cout
            << "["
            << (passed ? "PASS" : "FAIL")
            << "] "
            << description
            << "\n";

        allPassed = allPassed && passed;
    }

    if (!allPassed) {
        throw GitError("One or more validation checks failed.");
    }
}

static void demonstrateDiagnostic(
    const fs::path& repository
) {
    section("13. Repository diagnostic");

    const std::string branch =
        gitText(repository, {"branch", "--show-current"});

    const std::string head =
        shortHash(repository);

    const auto upstream = gitCommand(
        repository,
        {
            "rev-parse",
            "--abbrev-ref",
            "--symbolic-full-name",
            "@{u}"
        },
        false
    );

    std::cout << "Branch: " << branch << "\n";
    std::cout << "HEAD:   " << head << "\n";

    if (upstream.exitCode == 0) {
        std::cout
            << "Upstream: "
            << upstream.output;
    } else {
        std::cout << "Upstream: not configured\n";
    }

    std::cout << "\nStatus:\n";
    showStatus(repository);

    std::cout << "\nRecent history:\n";
    std::cout
        << gitText(
               repository,
               {"log", "--decorate", "--oneline", "-6"}
           )
        << "\n";

    std::cout << "\nUnstaged diff statistics:\n";
    const std::string unstaged =
        gitText(repository, {"diff", "--stat"});

    std::cout
        << (unstaged.empty() ? "(none)" : unstaged)
        << "\n";

    std::cout << "\nStaged diff statistics:\n";
    const std::string staged =
        gitText(
            repository,
            {"diff", "--cached", "--stat"}
        );

    std::cout
        << (staged.empty() ? "(none)" : staged)
        << "\n";
}

int main() {
    try {
        /*
         * Create a unique temporary directory. The demonstration never
         * operates on an existing user repository.
         */
        const fs::path temporaryDirectory =
            fs::temp_directory_path() /
            fs::path("git_history_cpp_learning");

        /*
         * A previous failed run should not contaminate the current
         * demonstration.
         */
        std::error_code cleanupError;
        fs::remove_all(temporaryDirectory, cleanupError);
        fs::create_directories(temporaryDirectory);

        /*
         * Confirm Git is installed.
         */
        const auto gitVersion =
            runShellCommand("git --version", temporaryDirectory);

        if (gitVersion.exitCode != 0) {
            throw GitError(
                "Git is not available on PATH.\n" +
                gitVersion.output
            );
        }

        std::cout
            << "Using "
            << gitVersion.output
            << "\n";

        explainRepositoryModel();

        const fs::path repository =
            createRepository(temporaryDirectory);

        std::cout
            << "\nTemporary repository: "
            << repository
            << "\n";

        demonstrateLog(repository);
        demonstrateShow(repository);
        demonstrateDiff(repository);
        demonstrateReset(repository);
        demonstrateRevert(repository);
        demonstrateRevisionExpressions(repository);
        demonstrateMergeHistory(repository);
        demonstrateFileHistory(repository);
        demonstratePrettyFormats(repository);
        demonstrateReflog(repository);
        demonstrateDiagnostic(repository);
        runValidation(repository);

        section("14. Final history");

        std::cout
            << gitText(
                   repository,
                   {
                       "log",
                       "--graph",
                       "--decorate",
                       "--oneline",
                       "--all"
                   }
               )
            << "\n";

        showStatus(repository);

        /*
         * The repository can now be removed because every demonstration has
         * already completed. The real lesson is the sequence of commands,
         * not persistence of this temporary repository.
         */
        fs::remove_all(temporaryDirectory, cleanupError);

        section("15. End of case study");
        std::cout
            << "All Git history demonstrations completed successfully.\n";

        return 0;
    }
    catch (const GitError& error) {
        std::cerr
            << "\nGit error:\n"
            << error.what()
            << "\n";

        return 1;
    }
    catch (const std::exception& error) {
        std::cerr
            << "\nUnexpected error:\n"
            << error.what()
            << "\n";

        return 1;
    }
}
